### ISSUE TITLE
Update BED-JSON to remove placeholders for data we don't currently have

### ISSUE THREAD

**Issue by RDmitchell** [building-envelope-data/api#273]
Prioirty = 4

**Comment by StephenCzarnecki** [comment]
@christoph-maurer Can you provide an example url that still has placeholder information?  So far I am not seeing any in the code and when I look at some samples from the server like

https://igsdb-icon.herokuapp.com/api/v1/products/4791/?json_format=buildingenvelopedata.org
or
https://igsdb-icon.herokuapp.com/api/v1/products/196/?json_format=buildingenvelopedata.org

I do not immediately see anything that looks like placeholder data.

**Comment by christoph-maurer** [comment]
@StephenCzarnecki I agree, I don't see placeholders anymore. I tried to validate https://igsdb-icon.herokuapp.com/api/v1/products/196/?json_format=buildingenvelopedata.org against the schema using `make shell` and `make test`. I had to change two things to make it valid. First, I deleted all lines `"transmittance": null,`, because `null` is not allowed and the key should be omitted if there is no data. Second, I exchanged `"solar"` by `{ "integral": "solar" }` and the same for `visible` and `infrared`. I have added the [original](https://github.com/building-envelope-data/api/blob/develop/tests/invalid/opticalData/igsdbExample196invalid.json) and the [corrected](https://github.com/building-envelope-data/api/blob/develop/tests/valid/opticalData/igsdbExample196.json) file to the tests and deleted [older examples](https://github.com/building-envelope-data/api/commit/5a0adbd6c27e7c663e474c170af6defc65e0ce62) from IGSDB.

**Comment by StephenCzarnecki** [comment]
@christoph-maurer This should hopefully be fixed now.  I had errors trying to run `make shell` when I cloned the repo so was not able to verify with `make test`.  But I have updated the json based on your comment so hopefully it is now correct.

**Comment by christoph-maurer** [comment]
@StephenCzarnecki It works fine, thank you!
@RDmitchell Stephen has solved the two remaining issues. Thanks to both of you for your contributions!
