### ISSUE TITLE
Update metabase.grapqhl

### ISSUE THREAD

**Issue by christoph-maurer** [building-envelope-data/api#332]
Before creating the release https://github.com/building-envelope-data/api/issues/333, [metabase.graphql](https://github.com/building-envelope-data/api/blob/develop/apis/metabase.graphql) should be updated from [type-defs.graphqls](https://github.com/building-envelope-data/metabase/blob/develop/frontend/type-defs.graphqls) .

@simon-wacker Is there already a description how to do it?

**Comment by simon-wacker** [comment]
[type-defs.graphqls](https://github.com/building-envelope-data/metabase/blob/develop/frontend/type-defs.graphqls) is updated by running `make schema` within the frontend container. [metabase.graphql](https://github.com/building-envelope-data/api/blob/develop/apis/metabase.graphql) is updated by just copying [type-defs.graphqls](https://github.com/building-envelope-data/metabase/blob/develop/frontend/type-defs.graphqls) with `cp` in a shell or in your WYSIWYG file browser. I don't know if there needs to be a description for that. It seems kind of obvious/redundant to me. Because we need to copy a file from one project to another and people clone there projects wherever they want to, there cannot be a simple shell command that works for everyone.

**Comment by christoph-maurer** [comment]
Thank you for the explanation @simon-wacker !

When I run
```
make shellb
make schema
```
in repo metabase, I get the error
```
me@682e099cfd12:~/app$ make schema
gq http://backend:8080/graphql/ --introspect > schema.graphql
/bin/sh: 1: gq: not found
make: *** [Makefile:151: schema] Error 127
```

**Comment by simon-wacker** [comment]
Ja, das target heisst `update-schema`.

**Comment by christoph-maurer** [comment]
metabase.graphql was updated with https://github.com/building-envelope-data/api/commit/cded5e6e4903bf7a66672ca19dc9317498f3e07d
